# Keep the host as the default target so shared protocol code can be tested locally.
[target.thumbv6m-none-eabi]
rustflags = ["-C", "link-arg=-Tlink.x"]

[alias]
build-dst-rev1 = "build -p dst-01 --target thumbv6m-none-eabi --no-default-features --features x4,rev1"
build-dst-rev2 = "build -p dst-01 --target thumbv6m-none-eabi --no-default-features --features x4,rev2"
build-psu = "build -p psu-01 --target thumbv6m-none-eabi --release"
build-boot-g0b1 = "build -p arc-boot --target thumbv6m-none-eabi --no-default-features --features g0b1 --release"
build-boot-c092 = "build -p arc-boot --target thumbv6m-none-eabi --no-default-features --features c092 --release"
