[package]
name = "arc-boot"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[features]
default = []
g0b1 = ["embassy-stm32/stm32g0b1re"]
c092 = ["embassy-stm32/stm32c092cb"]

[[bin]]
name = "arc-boot"
path = "src/main.rs"
test = false
bench = false

[dependencies]
embassy-boot-stm32.workspace = true
embassy-stm32.workspace = true
embassy-sync.workspace = true
cortex-m-rt.workspace = true
cortex-m.workspace = true
panic-halt.workspace = true
